# Fix compliation error about 'XKeysymToString' by linking X11 explicitly
# Thanks Antonio Ospite!
Import('env')
if env['X11']:
  config_string = 'pkg-config --cflags --libs x11'
  if env['PLATFORM'] == 'darwin':
    config_string = 'PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig/ ' + config_string
  env.ParseConfig(config_string)
Export('env')

source_list = Split(
    """
    input.cpp
    config.cpp
    sdl-joystick.cpp
    sdl-sound.cpp
    sdl-throttle.cpp
    sdl-video.cpp
    sdl-emscripten.cpp
    sdl-es2.cpp
    es2n.cpp
    es2utils.cpp
    """)

source_list = ['drivers/sdl/' + s for s in source_list]

# Need to include zlib functions.
zlib_source_list = Split(
"""
adler32.c
compress.c
crc32.c
deflate.c
gzio.c
infblock.c
infcodes.c
inffast.c
inflate.c
inftrees.c
infutil.c
trees.c
uncompr.c
zutil.c
""")
source_list += ['drivers/win/zlib/' + s for s in zlib_source_list]
Return('source_list')
