// List of em-fceux controllers (config interface) enums.
// Legend:
//   CTRL(ctrlId, enumName)
// NOTE: DO NOT CHANGE THE ORDER!
CONTROLLER_PRE
CONTROLLER( 0, BRIGHTNESS)
CONTROLLER( 1, CONTRAST)
CONTROLLER( 2, COLOR)
CONTROLLER( 3, GAMMA)
CONTROLLER( 4, GLOW)
CONTROLLER( 5, SHARPNESS)
CONTROLLER( 6, RGBPPU)
CONTROLLER( 7, CRT_ENABLED)
CONTROLLER( 8, SCANLINES)
CONTROLLER( 9, CONVERGENCE)
CONTROLLER(10, NOISE)
CONTROLLER(11, SOUND_ENABLED)
CONTROLLER(12, PORT2)
CONTROLLER_POST

